# Do not edit this file.
def load_native_module():
    import os.path
    import sys
    import imp
    fp = None
    try:
        native_module_name = '_' + os.path.splitext(os.path.basename(__file__))[0]
        fp, pathname, description = imp.find_module(native_module_name, [os.path.dirname(__file__)])
    except ImportError:
        import _fmodule
        return _fmodule
    if fp is not None:
        try:
            _mod = imp.load_module(native_module_name, fp, pathname, description)
        finally:
            fp.close()
        return _mod

_native_module = load_native_module()

import sys

for s in filter(lambda s: s not in set(['__doc__', '__file__', '__name__', '__package__']),
                dir(_native_module)):
    setattr(sys.modules[__name__], s, getattr(_native_module, s))

del _native_module
del sys
