# Do not edit this file but the section below between "EDIT BELOW" and "STOP EDITION HERE"
# unless you know what you are doing.

def load_native_module():
    import os.path
    import sys
    import imp
    fp = None
    try:
        native_module_name = '_' + os.path.splitext(os.path.basename(__file__))[0]
        fp, pathname, description = imp.find_module(native_module_name, [os.path.dirname(__file__)])
    except ImportError:
        import _fmodule
        return _fmodule
    if fp is not None:
        try:
            _mod = imp.load_module(native_module_name, fp, pathname, description)
        finally:
            fp.close()
        return _mod

_native_module = load_native_module()

# I can not figure out why, but _native_module instance appears
# to be the same across all loaded module.
# but fortran modules are different in each loaded instance.

# YOU MUST DECLARE YOUR FORTRAN MODULES BELOW.
# --- EDIT BELOW ------------

data = _native_module.data


# --- STOP EDITION HERE ----
del _native_module
del load_native_module
